<a href="https://colab.research.google.com/github/AntoniKingston/PyTorchCourse/blob/main/Chapter-0-excersises" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

Excersise 1.

In [2]:
shape = (7,7)
rand_tensor = torch.rand(shape)
print(rand_tensor)

tensor([[0.8150, 0.3824, 0.3365, 0.0322, 0.9155, 0.6375, 0.5169],
        [0.9222, 0.8831, 0.4435, 0.9938, 0.0218, 0.0496, 0.2862],
        [0.0579, 0.5131, 0.1225, 0.7343, 0.1057, 0.8998, 0.4752],
        [0.5607, 0.4645, 0.1375, 0.5389, 0.5677, 0.3263, 0.3756],
        [0.1204, 0.8307, 0.4494, 0.8998, 0.0131, 0.6234, 0.7840],
        [0.2912, 0.6589, 0.3399, 0.7591, 0.3501, 0.3750, 0.4060],
        [0.2928, 0.5100, 0.5779, 0.2524, 0.2945, 0.7526, 0.2659]])


In [3]:
shape = (7,7,)
rand_tensor = torch.rand(shape)
print(rand_tensor)

tensor([[0.9565, 0.7876, 0.1903, 0.6472, 0.4699, 0.4036, 0.6421],
        [0.5849, 0.0562, 0.8971, 0.2337, 0.3035, 0.6581, 0.3883],
        [0.7604, 0.4382, 0.7166, 0.5356, 0.5645, 0.4113, 0.1033],
        [0.6619, 0.6454, 0.6813, 0.3172, 0.1742, 0.1954, 0.7353],
        [0.1624, 0.1709, 0.5688, 0.4694, 0.5039, 0.6322, 0.5977],
        [0.7800, 0.2488, 0.6709, 0.0277, 0.4456, 0.7130, 0.3243],
        [0.8637, 0.9171, 0.9514, 0.6207, 0.2589, 0.1812, 0.3114]])


Ex. 2

In [4]:
shape2 = (1,7)
rand_tensor2 = torch.rand(shape2)
rand_tensor2 = rand_tensor2.T
result = torch.matmul(rand_tensor, rand_tensor2)
print(result)

tensor([[1.7655],
        [1.6268],
        [1.5735],
        [1.7290],
        [1.4087],
        [1.5810],
        [1.9579]])


Ex. 3.

In [5]:
torch.manual_seed(0)
shape = (7,7)
rand_tensor = torch.rand(shape)
print(rand_tensor)
shape2 = (1,7)
rand_tensor2 = torch.rand(shape2)
rand_tensor2 = rand_tensor2.T
result = torch.matmul(rand_tensor, rand_tensor2)
print(result)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


Ex. 4.

In [6]:
torch.cuda.manual_seed(1234)

Ex. 5,6

In [8]:
torch.manual_seed(1234)
tensor1 = torch.rand((2,3))
tensor2 = torch.rand((2,3))
tensor1.to('cuda')
tensor2.to('cuda')
tensor2 = tensor2.T
result = torch.matmul(tensor1, tensor2)
print(result)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


Ex. 7.

In [9]:
maks = torch.max(result)
print(maks)
mini = torch.min(result)
print(mini)

tensor(0.5617)
tensor(0.3647)


Ex. 8.

In [10]:
armaks = torch.argmax(result)
print(armaks)
armini = torch.argmin(result)
print(armini)


tensor(3)
tensor(0)


Ex. 9.

In [11]:
torch.manual_seed(7)
tensor1 = torch.rand((1,1,1,10))
print(tensor1)
print(tensor1.shape)
tensor2 = torch.squeeze(tensor1)
print(tensor2)
print(tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
